allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.evaluationDependsOn(':app')
}
gradle.projectsEvaluated {
    subprojects.each { project ->
        if (project.plugins.hasPlugin('com.android.library')) {
            project.android.buildTypes.release.minifyEnabled = false
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
